# Generated by Django 3.0.6 on 2020-09-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20200913_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
